repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["rq_core"]
        pass_filenames: false
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: local
    hooks:
      - id: trading-safety-static-check
        name: Trading safety static check
        entry: python src/scripts/quality/trading_safety_static_check.py
        language: python
        pass_filenames: false
      - id: markdown-docs-check
        name: Markdown docs check
        entry: python src/scripts/quality/markdown_docs_check.py
        language: python
        pass_filenames: false
